######################################################################
# Automatically generated by qmake (2.01a) ? 10? 29 00:00:33 2012
######################################################################

QT += core gui testlib

TEMPLATE = app
TARGET = malachite-test

include(../malachite-exec.pri)

SOURCES += \
    test.cpp

HEADERS += \
    test.h
