######################################################################
# Automatically generated by qmake (2.01a) ? 2? 14 17:52:09 2013
######################################################################

TARGET = paintfield-colorui

include(../extensions.pri)

# Input
HEADERS += colorsidebar.h coloruiextension.h
SOURCES += colorsidebar.cpp coloruiextension.cpp
