
PF_PWD_ROOT = $$PWD/../..
PF_OUT_PWD_ROOT = $$PF_OUT_PWD/../..

!isEmpty(QMAKE_POST_LINK) {
	QMAKE_POST_LINK += ";"
}

QMAKE_POST_LINK += "ruby $$PF_PWD_ROOT/scripts/postlink.rb $$PF_PWD_ROOT $$PF_OUT_PWD_ROOT $$VERSION $$PF_PLATFORM $$PF_DEBUG_OR_RELEASE"
