######################################################################
# Automatically generated by qmake (2.01a) ? 2? 14 17:51:44 2013
######################################################################

TARGET = paintfield-aboutdialog

include(../extensions.pri)

# Input
HEADERS += aboutdialog.h aboutdialogextension.h
FORMS += aboutdialog.ui
SOURCES += aboutdialog.cpp aboutdialogextension.cpp
