######################################################################
# Automatically generated by qmake (2.01a) ? 2? 14 17:52:37 2013
######################################################################

TARGET = paintfield-navigator

include(../extensions.pri)

# Input
HEADERS += navigatorcontroller.h navigatorextension.h navigatorview.h
SOURCES += navigatorcontroller.cpp navigatorextension.cpp navigatorview.cpp
