######################################################################
# Automatically generated by qmake (2.01a) ? 2? 14 17:52:30 2013
######################################################################

TARGET = paintfield-movetool

include(../extensions.pri)

# Input
HEADERS += layermovetool.h layermovetoolextension.h
SOURCES += layermovetool.cpp layermovetoolextension.cpp
