######################################################################
# Automatically generated by qmake (2.01a) ? 2? 14 17:52:45 2013
######################################################################

TARGET = paintfield-vectortools

include(../extensions.pri)

HEADERS += \
    vectortoolsextension.h \
    recttool.h

SOURCES += \
    vectortoolsextension.cpp \
    recttool.cpp
