######################################################################
# Automatically generated by qmake (2.01a) ? 2? 14 17:52:45 2013
######################################################################

TARGET = paintfield-toolui

include(../extensions.pri)

# Input
HEADERS += tooluiextension.h
SOURCES += tooluiextension.cpp
